include: package:flutter_lints/flutter.yaml

linter:
  rules:
    sort_constructors_first: true
    prefer_single_quotes: true
    always_specify_types: true
    lines_longer_than_80_chars: false
    always_put_required_named_parameters_first: true
    camel_case_types: true
    library_names: true
    avoid_positional_boolean_parameters: true
    sized_box_for_whitespace: true
    no_logic_in_create_state: true
    file_names: false
    avoid_empty_else: true
    avoid_print: false
    use_build_context_synchronously: false
    require_trailing_commas: true

analyzer:
  plugins:
    - custom_lint