name: coach_potato
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  firebase_auth: ^5.5.1
  sqflite: ^2.4.1
  path: ^1.9.0
  flutter_localizations:
    sdk: flutter
  intl: any
  go_router: ^14.8.1
  firebase_core: ^3.12.1
  cloud_firestore: ^5.6.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  riverpod_generator: ^2.6.4
  build_runner: ^2.4.15
  custom_lint: ^0.7.3
  riverpod_lint: ^2.6.4
  sqflite_common_ffi_web: ^0.4.5+4
  faker: ^2.2.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/exercises.json

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic